# config context path to "/" by setting an empty string
server:
  contextPath: /
  port: 8081
# JACKSON
spring:
  datasource:
      url: jdbc:mysql://192.168.154.131:3306/test?useSSL=false&characterEncoding=UTF-8
      driver-class-name: com.mysql.jdbc.Driver
      username: root
      password: root
  jackson:
    serialization:
      INDENT_OUTPUT: true
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    database: mysql

jwt:
  header: Authorization
  secret: mySecret
  expiration: 604800
  route:
    authentication:
      path: auth
      refresh: refresh

#logging:
#  level:
#    org.springframework:
#      security: DEBUG